backward_num_day: 5
df_path: ./data/data/BTC/test_feature.csv
forward_num_day: 5
future_weights: 0.2
initial_amount: 100000
max_volume: 1
tech_indicator_list:
# - high
# - low
# - open
# - close
# - adjcp
- zopen
- zhigh
- zlow
- zadjcp
- zclose
- zd_5
- zd_10
- zd_15
- zd_20
- zd_25
- zd_30
- autoFE_f_0
- autoFE_f_1
- autoFE_f_2
- autoFE_f_3
- autoFE_f_4
- autoFE_f_5
- autoFE_f_6
- autoFE_f_7
- autoFE_f_8
- autoFE_f_9
- autoFE_f_10
- autoFE_f_11
- autoFE_f_12
- autoFE_f_13
- autoFE_f_14
- autoFE_f_15
- autoFE_f_16
- autoFE_f_17
- autoFE_f_18
- autoFE_f_19
- autoFE_f_20
- autoFE_f_21
- autoFE_f_22
- autoFE_f_23
- autoFE_f_24
- autoFE_f_25
- autoFE_f_26
- autoFE_f_27
- autoFE_f_28
- autoFE_f_29
- autoFE_f_30
- autoFE_f_31
- autoFE_f_32
- autoFE_f_33
- autoFE_f_34
- autoFE_f_35
- autoFE_f_36
- autoFE_f_37
- autoFE_f_38
- autoFE_f_39
- autoFE_f_40
- autoFE_f_41
- autoFE_f_42
- autoFE_f_43
- autoFE_f_44
- autoFE_f_45
- autoFE_f_46
- autoFE_f_47
- autoFE_f_48
- autoFE_f_49
- autoFE_f_50
- autoFE_f_51
- autoFE_f_52
- autoFE_f_53
- autoFE_f_54
- autoFE_f_55
- autoFE_f_56
- autoFE_f_57
- autoFE_f_58
- autoFE_f_59
- autoFE_f_60
- autoFE_f_61
- autoFE_f_62
- autoFE_f_63
- autoFE_f_64
- autoFE_f_65
- autoFE_f_66
- autoFE_f_67
- autoFE_f_68
- autoFE_f_69
- autoFE_f_70
- autoFE_f_71
- autoFE_f_72
- autoFE_f_73
- autoFE_f_74
- autoFE_f_75
- autoFE_f_76
- autoFE_f_77
- autoFE_f_78
- autoFE_f_79
- autoFE_f_80
- autoFE_f_81
- autoFE_f_82
- autoFE_f_83
- autoFE_f_84
- autoFE_f_85
- autoFE_f_86
- autoFE_f_87
- autoFE_f_88
- autoFE_f_89
- autoFE_f_90
- autoFE_f_91
- autoFE_f_92
- autoFE_f_93
- autoFE_f_94
- autoFE_f_95
- autoFE_f_96
- autoFE_f_97
- autoFE_f_98
- autoFE_f_99
transaction_cost_pct: 0.001
