name: TradeMaster
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.23.5
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - gymnasium
  - lightgbm
  - jupyterlab
  - ipykernel
  - statsmodels
  - ffmpeg
  - cudatoolkit=11.8  # CUDA support
  - pillow
  - cffi
  - setuptools
  - cython
  - typing-extensions
  - pip:
      - mmcv==1.7.1
      - diffusers==0.25.1
      - transformers==4.36.2
      - ray==2.0.0
      - wandb
      - optuna
      - tslearn
      - fastdtw
      - iopath
      - plotly
      - yfinance
      - yapf==0.30.0
